name: mscic-wgs
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  - more-itertools
  - attrs
  - numpy
  - pandas
  - scikit-learn
  - pysam
  - tqdm
  - scipy
  - seaborn
  - matplotlib
  - statsmodels
  - hail >= 0.2.58
  - r-base
  - r-tidyverse
  - r-foreach
  - r-doparallel
  - r-ggplot2
  - r-rmpi
  - bioconductor-genesis
  - bioconductor-seqarray
  - bioconductor-seqvartools
  - bioconductor-snprelate
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-genomicranges
  - r-qqman