cluster: "snakemake_bsub_wrapper.py"
cluster-status: "cluster_status.py"
jobs: 1000
local-cores: 48
default-resources:
    - mem_mb=8000
    - time_min=720
    - cpus=1
    - queue="premium"
    - project="mscic"
config:
    - hail_task_script="hail_wgs.py"
    - genesis_task_script="seqarray_genesis.R"
    - hail_wrapper="lsf_hail_wrapper.py"