cluster: "snakemake_bsub_wrapper.py"
cluster-status: "cluster_status.py"
jobs: 1000
local-cores: 48
latency-wait: 30
default-resources:
    - mem_mb=8000
    - time_min=720
    - cpus=1
    - queue="premium"
    - project="mscic"
config:
    - scriptsdir="/sc/arion/projects/mscic1/scripts/WGS"
    - resourcesdir="/sc/arion/projects/mscic1/resources"
